# Generated by Django 6.0.5 on 2026-05-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cropupload_mobile_alter_farmer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
