# Generated by Django 6.0.5 on 2026-05-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_farmer_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropupload',
            old_name='crop_type',
            new_name='crop_name',
        ),
        migrations.RemoveField(
            model_name='cropupload',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cropupload',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='cropupload',
            name='village',
        ),
        migrations.AlterField(
            model_name='cropupload',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cropupload',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
