# Generated by Django 6.0.5 on 2026-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_crop_type_cropupload_crop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropupload',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
