# Generated by Django 6.0.5 on 2026-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cropupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropupload',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cropupload',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cropupload',
            name='village',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cropupload',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
